schema_version: 1

context:
  version: "0.4.0"

package:
  name: jupyterlite-pdf-exporter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlite-pdf-exporter/jupyterlite_pdf_exporter-${{ version }}.tar.gz
  sha256: 5486c868f501d9cb1bed30a6a26960aa46e0f894abc8d917638ec4fd93d27e4b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - jupyter-builder >=1.2.0,<2
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - jupyterlite_pdf_exporter
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A PDF exporter for JupyterLite based on WebAssembly distributions of Pandoc and Typst.
  license: GPL-2.0-or-later
  license_file:
    - LICENSE-TYPST.txt
    - LICENSE-PANDOC.txt
    - LICENSE.txt
    - jupyterlite_pdf_exporter/labextension/static/third-party-licenses.json
  homepage: https://github.com/agriyakhetarpal/jupyterlite-pdf-exporter

extra:
  recipe-maintainers:
    - agriyakhetarpal
